/**
 * Account statements — one per supplier per event, and one per client per event.
 *
 * A statement is the answer to "what do you owe me, and how did you get there?"
 * put in writing: the event it belongs to, the amounts, and the payments or
 * invoices behind them. It exists so a figure can leave the tracker with its
 * reasoning attached, rather than as a number in an email.
 *
 * It is a **PDF**, because it leaves the company. A supplier reads it, files it,
 * and quotes it back; a client's accounts payable attaches it to a payment run.
 * A spreadsheet is the wrong artifact for that — the ledger exports elsewhere in
 * the tracker are CSV precisely because those are for reconciling, not for
 * sending.
 *
 * Pure: shapes in, bytes out. Nothing here knows about the DOM.
 */
import { buildPdf, type Block } from "./pdf";
import type { ZipEntry } from "./zip";

export type StatementEvent = {
  ref: string;
  client: string;
  eventType?: string | null;
  dates?: string | null;
  po?: string | null;
  poDate?: string | null;
  currency?: string | null;
};

export type StatementPayment = {
  amount?: number | null;
  paidOn?: string | null;
  method?: string | null;
  reference?: string | null;
};

export type StatementSupplier = {
  name: string;
  email?: string | null;
  currency?: string | null;
  /** Everything the supplier is owed on this event, before anything was paid. */
  payable?: number | null;
  due?: number | null;
  paid?: number | null;
  /** Marketplace NA only: our cut, and what is left to claw back. */
  commission?: number | null;
  commissionToRecover?: number | null;
  refundToRecover?: number | null;
  payments?: StatementPayment[];
};

export type StatementInvoice = {
  ref?: string | null;
  status?: string | null;
  issued?: string | null;
  sent?: string | null;
  due?: string | null;
  amount?: number | null;
};

export type StatementClient = {
  invoiced?: number | null;
  collected?: number | null;
  outstanding?: number | null;
  invoices?: StatementInvoice[];
};

/** Grouped thousands and two decimals — a figure on a document, not in a cell. */
function amount(value: number | null | undefined, currency?: string | null): string {
  if (value == null) return "—";
  const figure = new Intl.NumberFormat("fr-CA", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
    .format(value)
    .replace(/[\u00a0\u202f]/g, " ");
  return currency ? `${figure} ${currency}` : figure;
}

/** Filenames go into a zip and onto someone's desktop: keep them harmless. */
export function safeFileName(text: string): string {
  return (
    text
      .replace(/[/\\?%*:|"<>]/g, "-")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 80) || "statement"
  );
}

/** The block every statement opens with: who it is for, and what it is about. */
function header(event: StatementEvent, kind: string, subject: string): Block[] {
  const facts: Array<[string, string]> = [
    ["Event", event.ref],
    ["Client", event.client],
  ];
  if (event.eventType) facts.push(["Event type", event.eventType]);
  if (event.dates) facts.push(["Dates", event.dates]);
  if (event.po) facts.push(["Purchase order", event.po]);
  if (event.poDate) facts.push(["PO received", event.poDate]);

  return [
    { kind: "title", text: "Naboo — account statement" },
    { kind: "subtitle", text: `${kind} · ${subject}` },
    { kind: "rule", strong: true },
    { kind: "space", height: 8 },
    ...facts.map(([label, value]): Block => ({
      kind: "row",
      cells: [
        { text: label, width: 0.3 },
        { text: value, width: 0.7, font: "mono" },
      ],
    })),
    { kind: "space", height: 14 },
  ];
}

const GENERATED = "Generated by the Naboo tracker from the booking's own ledger.";

export function supplierStatement(event: StatementEvent, supplier: StatementSupplier): ZipEntry {
  const ccy = supplier.currency ?? event.currency ?? null;
  const blocks: Block[] = [
    ...header(event, "Supplier statement", supplier.name),
    ...(supplier.email
      ? [
          {
            kind: "row" as const,
            cells: [
              { text: "Contact", width: 0.3 },
              { text: supplier.email, width: 0.7, font: "mono" as const },
            ],
          },
          { kind: "space" as const, height: 14 },
        ]
      : []),
    { kind: "label", text: `What is owed${ccy ? ` — ${ccy}` : ""}` },
    { kind: "rule" },
  ];

  if (supplier.payable != null) {
    blocks.push({
      kind: "kv",
      label: "Total payable for this event",
      value: amount(supplier.payable),
    });
  }
  if (supplier.commission != null) {
    blocks.push({ kind: "kv", label: "Naboo commission", value: amount(supplier.commission) });
  }
  blocks.push({ kind: "kv", label: "Paid by Naboo", value: amount(supplier.paid ?? 0) });
  blocks.push({ kind: "rule" });
  blocks.push({
    kind: "kv",
    label: "Still due",
    value: amount(supplier.due ?? 0),
    strong: true,
  });

  if ((supplier.commissionToRecover ?? 0) > 0.01) {
    blocks.push({
      kind: "kv",
      label: "Commission to recover from the supplier",
      value: amount(supplier.commissionToRecover),
      strong: true,
      alert: true,
    });
  }
  if ((supplier.refundToRecover ?? 0) > 0.01) {
    blocks.push({
      kind: "kv",
      label: "Overpayment to refund to Naboo",
      value: amount(supplier.refundToRecover),
      strong: true,
      alert: true,
    });
  }

  const payments = supplier.payments ?? [];
  if (payments.length > 0) {
    blocks.push({ kind: "space", height: 20 });
    blocks.push({ kind: "label", text: "Payments made" });
    blocks.push({ kind: "rule" });
    blocks.push({
      kind: "row",
      header: true,
      cells: [
        { text: "Date", width: 0.2 },
        { text: "Method", width: 0.25 },
        { text: "Reference", width: 0.3 },
        { text: "Amount", width: 0.25, align: "right" },
      ],
    });
    for (const p of payments) {
      blocks.push({
        kind: "row",
        cells: [
          { text: p.paidOn ?? "—", width: 0.2, font: "mono" },
          { text: p.method ?? "—", width: 0.25 },
          { text: p.reference ?? "—", width: 0.3, font: "mono" },
          { text: amount(p.amount), width: 0.25, align: "right", font: "mono" },
        ],
      });
    }
    blocks.push({ kind: "rule" });
  }

  blocks.push({ kind: "space", height: 18 });
  blocks.push({
    kind: "note",
    text: "Amounts are shown inclusive of tax, in the currency named above. If anything here disagrees with your own records, reply to this statement and we will reconcile it line by line.",
  });

  return {
    name: `${safeFileName(supplier.name)} — ${safeFileName(event.ref)}.pdf`,
    bytes: buildPdf(blocks, GENERATED),
  };
}

export function clientStatement(event: StatementEvent, client: StatementClient): ZipEntry {
  const ccy = event.currency ?? null;
  const blocks: Block[] = [
    ...header(event, "Client statement", event.client),
    { kind: "label", text: `Position${ccy ? ` — ${ccy}` : ""}` },
    { kind: "rule" },
    { kind: "kv", label: "Invoiced", value: amount(client.invoiced ?? 0) },
    { kind: "kv", label: "Received", value: amount(client.collected ?? 0) },
    { kind: "rule" },
    { kind: "kv", label: "Outstanding", value: amount(client.outstanding ?? 0), strong: true },
  ];

  const invoices = client.invoices ?? [];
  if (invoices.length > 0) {
    blocks.push({ kind: "space", height: 20 });
    blocks.push({ kind: "label", text: "Invoices" });
    blocks.push({ kind: "rule" });
    blocks.push({
      kind: "row",
      header: true,
      cells: [
        { text: "Reference", width: 0.26 },
        { text: "Status", width: 0.14 },
        { text: "Issued", width: 0.15 },
        { text: "Sent", width: 0.15 },
        { text: "Payment due", width: 0.15 },
        { text: "Amount", width: 0.15, align: "right" },
      ],
    });
    for (const i of invoices) {
      blocks.push({
        kind: "row",
        cells: [
          { text: i.ref ?? "—", width: 0.26, font: "mono" },
          { text: (i.status ?? "").toLowerCase() || "—", width: 0.14 },
          { text: i.issued ?? "—", width: 0.15, font: "mono" },
          { text: i.sent ?? "—", width: 0.15, font: "mono" },
          { text: i.due ?? "—", width: 0.15, font: "mono" },
          { text: amount(i.amount), width: 0.15, align: "right", font: "mono" },
        ],
      });
    }
    blocks.push({ kind: "rule" });
  } else {
    blocks.push({ kind: "space", height: 16 });
    blocks.push({ kind: "note", text: "No invoice has been issued on this event yet." });
  }

  blocks.push({ kind: "space", height: 18 });
  blocks.push({
    kind: "note",
    text: "Amounts are shown inclusive of tax, in the currency named above. Payment terms run from the date each invoice was sent.",
  });

  return {
    name: `${safeFileName(event.client)} — ${safeFileName(event.ref)}.pdf`,
    bytes: buildPdf(blocks, GENERATED),
  };
}

/** `statements-supplier-2026-08-18.zip` */
export function archiveName(kind: "supplier" | "client" | "all", today: string): string {
  return `statements-${kind}-${today}.zip`;
}
