import { buildPdf } from "./pdf.ts";

let pass = 0,
  fail = 0;
const t = (name, cond, got = "") => {
  if (cond) {
    pass++;
    console.log("  ✓", name);
  } else {
    fail++;
    console.log("  ✗", name, got);
  }
};

const read = (bytes) => Buffer.from(bytes).toString("latin1");

const PAGE_WIDTH = 595.28;
const MARGIN = 56;
const RIGHT = PAGE_WIDTH - MARGIN;

/** Every `Tm` placement in the file, with the string it places. */
function placements(pdf) {
  const out = [];
  const re = /\/(F\d) ([\d.]+) Tf 1 0 0 1 ([\d.-]+) ([\d.-]+) Tm \(((?:[^()\\]|\\.)*)\) Tj/g;
  let m;
  while ((m = re.exec(pdf)) != null) {
    const [, font, size, x, y, text] = m;
    // Escapes are one byte each, whatever their spelling.
    const length = text.replace(/\\[0-7]{3}/g, "x").replace(/\\./g, "x").length;
    out.push({ font, size: Number(size), x: Number(x), y: Number(y), length });
  }
  return out;
}

const doc = read(
  buildPdf(
    [
      { kind: "title", text: "Naboo — account statement" },
      { kind: "subtitle", text: "Supplier statement · Traiteur Agnus Dei" },
      { kind: "rule", strong: true },
      { kind: "kv", label: "Total payable for this event", value: "1 234 567,89" },
      { kind: "kv", label: "Still due", value: "999,00", strong: true },
      {
        kind: "row",
        header: true,
        cells: [
          { text: "Date", width: 0.5 },
          { text: "Amount", width: 0.5, align: "right" },
        ],
      },
      {
        kind: "row",
        cells: [
          { text: "2026-06-03", width: 0.5, font: "mono" },
          { text: "40 658,00", width: 0.5, align: "right", font: "mono" },
        ],
      },
      { kind: "note", text: "Amounts are shown inclusive of tax. ".repeat(6) },
    ],
    "Generated by the Naboo tracker.",
  ),
);

// ── The file ───────────────────────────────────────────────────────────────
t("it declares a PDF version", doc.startsWith("%PDF-1."));
t("it has a catalog, a page tree and a page", doc.includes("/Type /Catalog") && doc.includes("/Type /Pages") && doc.includes("/Type /Page "));
t("it has a cross-reference table and a trailer", doc.includes("\nxref\n") && doc.includes("/Root 1 0 R"));

// A reader trusts the xref offsets: each has to land on its object header.
const xref = doc.slice(doc.indexOf("\nxref\n") + 6);
const offsets = [...xref.matchAll(/^(\d{10}) 00000 n $/gm)].map((m) => Number(m[1]));
t("the file declares one offset per object", offsets.length > 3, String(offsets.length));
t(
  "every offset lands on its own object header",
  offsets.every((offset, i) => doc.slice(offset).startsWith(`${i + 1} 0 obj`)),
);
const startxref = Number(doc.match(/startxref\n(\d+)/)[1]);
t("startxref points at the table", doc.slice(startxref).startsWith("xref"));

// ── The layout ─────────────────────────────────────────────────────────────
const placed = placements(doc);
t("every block was placed", placed.length >= 10, String(placed.length));
t(
  "nothing starts left of the margin",
  placed.every((p) => p.x >= MARGIN - 0.01),
  JSON.stringify(placed.filter((p) => p.x < MARGIN - 0.01)),
);
t(
  "nothing runs past the right margin",
  placed.every((p) => p.x + p.length * p.size * (p.font === "F3" ? 0.6 : 0.5) <= RIGHT + 1),
);

// Courier is exactly 0.6 em per glyph, so a right-aligned figure lands on the
// margin to the point — which is what makes a column of amounts line up.
const figures = placed.filter((p) => p.font === "F3");
t("figures are set in the monospaced font", figures.length >= 3, String(figures.length));
t(
  "a right-aligned figure ends exactly on the right margin",
  figures.some((p) => Math.abs(p.x + p.length * p.size * 0.6 - RIGHT) < 0.05),
  JSON.stringify(figures.map((p) => (p.x + p.length * p.size * 0.6).toFixed(2))),
);
t(
  "amounts of different lengths align on their right edge",
  new Set(
    figures
      .filter((p) => p.size >= 10)
      .map((p) => (p.x + p.length * p.size * 0.6).toFixed(1)),
  ).size === 1,
);

// ── Paging ─────────────────────────────────────────────────────────────────
const long = read(
  buildPdf(
    Array.from({ length: 80 }, (_, i) => ({
      kind: "kv",
      label: `Line ${i + 1}`,
      value: "1 000,00",
    })),
    "footer",
  ),
);
const pageCount = (long.match(/\/Type \/Page /g) ?? []).length;
t("a long statement breaks onto further pages", pageCount > 1, String(pageCount));
t("the page tree counts them", long.includes(`/Count ${pageCount}`));
t("a multi-page statement numbers its pages", long.includes("1 / " + pageCount));

console.log(`\n${pass} passed, ${fail} failed`);
if (fail) process.exitCode = 1;
