/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVeoliaRouteImport } from './routes/_authenticated/veolia'
import { Route as AuthenticatedTrackingNorthAmericaRouteImport } from './routes/_authenticated/tracking-north-america'
import { Route as AuthenticatedNaCommissionsRouteImport } from './routes/_authenticated/na-commissions'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStatementRefRouteImport } from './routes/_authenticated/statement.$ref'
import { Route as AuthenticatedCommissionRefHouseCodeRouteImport } from './routes/_authenticated/commission.$ref.$houseCode'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeoliaRoute = AuthenticatedVeoliaRouteImport.update({
  id: '/veolia',
  path: '/veolia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackingNorthAmericaRoute =
  AuthenticatedTrackingNorthAmericaRouteImport.update({
    id: '/tracking-north-america',
    path: '/tracking-north-america',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNaCommissionsRoute =
  AuthenticatedNaCommissionsRouteImport.update({
    id: '/na-commissions',
    path: '/na-commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementRefRoute =
  AuthenticatedStatementRefRouteImport.update({
    id: '/statement/$ref',
    path: '/statement/$ref',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommissionRefHouseCodeRoute =
  AuthenticatedCommissionRefHouseCodeRouteImport.update({
    id: '/commission/$ref/$houseCode',
    path: '/commission/$ref/$houseCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/na-commissions': typeof AuthenticatedNaCommissionsRoute
  '/tracking-north-america': typeof AuthenticatedTrackingNorthAmericaRoute
  '/veolia': typeof AuthenticatedVeoliaRoute
  '/statement/$ref': typeof AuthenticatedStatementRefRoute
  '/commission/$ref/$houseCode': typeof AuthenticatedCommissionRefHouseCodeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/na-commissions': typeof AuthenticatedNaCommissionsRoute
  '/tracking-north-america': typeof AuthenticatedTrackingNorthAmericaRoute
  '/veolia': typeof AuthenticatedVeoliaRoute
  '/': typeof AuthenticatedIndexRoute
  '/statement/$ref': typeof AuthenticatedStatementRefRoute
  '/commission/$ref/$houseCode': typeof AuthenticatedCommissionRefHouseCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/na-commissions': typeof AuthenticatedNaCommissionsRoute
  '/_authenticated/tracking-north-america': typeof AuthenticatedTrackingNorthAmericaRoute
  '/_authenticated/veolia': typeof AuthenticatedVeoliaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/statement/$ref': typeof AuthenticatedStatementRefRoute
  '/_authenticated/commission/$ref/$houseCode': typeof AuthenticatedCommissionRefHouseCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/na-commissions'
    | '/tracking-north-america'
    | '/veolia'
    | '/statement/$ref'
    | '/commission/$ref/$houseCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/na-commissions'
    | '/tracking-north-america'
    | '/veolia'
    | '/'
    | '/statement/$ref'
    | '/commission/$ref/$houseCode'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/na-commissions'
    | '/_authenticated/tracking-north-america'
    | '/_authenticated/veolia'
    | '/_authenticated/'
    | '/_authenticated/statement/$ref'
    | '/_authenticated/commission/$ref/$houseCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veolia': {
      id: '/_authenticated/veolia'
      path: '/veolia'
      fullPath: '/veolia'
      preLoaderRoute: typeof AuthenticatedVeoliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracking-north-america': {
      id: '/_authenticated/tracking-north-america'
      path: '/tracking-north-america'
      fullPath: '/tracking-north-america'
      preLoaderRoute: typeof AuthenticatedTrackingNorthAmericaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/na-commissions': {
      id: '/_authenticated/na-commissions'
      path: '/na-commissions'
      fullPath: '/na-commissions'
      preLoaderRoute: typeof AuthenticatedNaCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statement/$ref': {
      id: '/_authenticated/statement/$ref'
      path: '/statement/$ref'
      fullPath: '/statement/$ref'
      preLoaderRoute: typeof AuthenticatedStatementRefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commission/$ref/$houseCode': {
      id: '/_authenticated/commission/$ref/$houseCode'
      path: '/commission/$ref/$houseCode'
      fullPath: '/commission/$ref/$houseCode'
      preLoaderRoute: typeof AuthenticatedCommissionRefHouseCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedNaCommissionsRoute: typeof AuthenticatedNaCommissionsRoute
  AuthenticatedTrackingNorthAmericaRoute: typeof AuthenticatedTrackingNorthAmericaRoute
  AuthenticatedVeoliaRoute: typeof AuthenticatedVeoliaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStatementRefRoute: typeof AuthenticatedStatementRefRoute
  AuthenticatedCommissionRefHouseCodeRoute: typeof AuthenticatedCommissionRefHouseCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedNaCommissionsRoute: AuthenticatedNaCommissionsRoute,
  AuthenticatedTrackingNorthAmericaRoute:
    AuthenticatedTrackingNorthAmericaRoute,
  AuthenticatedVeoliaRoute: AuthenticatedVeoliaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStatementRefRoute: AuthenticatedStatementRefRoute,
  AuthenticatedCommissionRefHouseCodeRoute:
    AuthenticatedCommissionRefHouseCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
